### ISSUE TITLE
[Info] Any info on the state of the project ?

### ISSUE THREAD

**Issue by zoqin** [TheFluffycart55/Runes-And-Dunes-1.20.X#1]
Hello, 

I stumble on your project and I saw great potential on your project
I was wondering in what state it was ? and if we could hope to see it evolve ?

Anyway the work you already done was great and it would have been a pleasure to experience your final vision
Have a nice day

**Comment by TheFluffycart55** [comment]
Greetings,
First off I want to say I'm so glad you've enjoyed my mod so far! I know it's been a bit of radio silence lately but that's just do to life picking up for me IRL. The good news is that I do have a few features I plan to get.pushed out in the coming weeks, and I'm really excited for the future of the mod now! Aiming for a rough release date of March 12th.

Once again, thank you so much for your interest and I hope that things can live up to your expectations!
-TheFluffyCart55

**Comment by zoqin** [comment]
Your welcome it's a pleasure 

Your well being and real life is the priority

I can't wait to test the updated version when it's ready and i'm happy to get news about the project

Take good care
